vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cryptos_images:
            uri_prefix: '%cryptos_images%'
            upload_destination: '%kernel.project_dir%/public%cryptos_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
